#pragma once

typedef enum
{
	epNone = 0, //По нулевому адресу хранится признак, что память инициализирована
	epSpentAh = 1,
	epSpentAhRest = 2,
	epSpentWh = 3,
	epSpentWhRest = 4,
	epTotalAh = 5,
	epRegenAh = 6,
	epRegenAhRest = 7,
	epRegenWh = 8,
	epRegenWhRest = 9,
	epCurrentMax = 10,
	epCurrentMin = 11,
	epVoltageMin = 12,
	epVoltageMax = 13,
	epSpentTime = 14,
	epDistance = 15,
	epTotalDistance = 16,
	epVelocityMax = 17,
	epTimeOnRoad = 18,
	epCycleCount = 19,
	epWheelLength = 20,
	epRotationPoles = 21,
	epCurrentMkV4A = 22,
	epBatteryCapacity = 23,
	epChargedVoltage = 24,
	epScaleMaxVelocity = 25,
	epScaleMinCurrent = 26,
	epScaleMinPower = 27,
	epScaleMaxCurrent = 28,
	epScaleMaxPower = 29,
	epZeroCurrentOffset = 30,
	epCalibrateVoltageMultiplier = 31,
	epZeroCurrentOffsetTemperature = 33,
	epOptions = 34,
	epCurrentZeroTemperatureCorrection = 35,
	epTempSensorType = 36,
	epMinFixedCurrent = 37,

	//Start BMS parameters
	epBmsCellCount = 50,
	epBmsLevelMin = 51,
	epBmsLevelMax = 52,
	epBmsLevelBalansing = 53,
	epBmsLevelCharged = 54,
	epBmsLevelReserved1 = 55,
	epBmsLevelReserved2 = 56,
	epBmsLevelReserved3 = 57,
	epBmsLevelReserved4 = 58,
	epBmsInp1Source = 59,
	epBmsInp2Source = 60,
	epBmsInp3Source = 61,
	epBmsInp4Source = 62,
	epBmsOut1Type = 63,
	epBmsOut2Type = 64,
	epBmsPwm1Type = 65,
	epBmsPwm1StartPwm = 66,
	epBmsPwm1HoldPwm = 67,
	epBmsPwm1StartTime = 68,
	epBmsPwm2Type = 69,
	epBmsPwm2StartPwm = 70,
	epBmsPwm2HoldPwm = 71,
	epBmsPwm2StartTime = 72,
	//End BMS parameters

	epEnd = 73,

	epLinkedKeysStorage = 100,
} EepromParameters;
